/**
 * Fetches enemy data from genshin-db-api and writes
 * src/data/enemies.js. Run with: npm run fetch:enemies
 *
 * Change API_BASE when self-hosting the API.
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const API_BASE = 'https://genshin-db-api.vercel.app/api/v5';
const ICON_BASE = 'https://gi.yatta.moe/assets/UI/monster/';
const CONCURRENCY = 5;

/**
 * Fetch with concurrency limit.
 */
async function fetchAll(names) {
  const results = [];
  for (let i = 0; i < names.length; i += CONCURRENCY) {
    const batch = names.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.all(
      batch.map(async (name) => {
        const url = `${API_BASE}/enemies?query=${encodeURIComponent(name)}`;
        const res = await fetch(url);
        if (!res.ok) {
          console.warn(`  ⚠ Failed to fetch "${name}" (${res.status})`);
          return null;
        }
        return res.json();
      })
    );
    results.push(...batchResults);
    if (i + CONCURRENCY < names.length) {
      process.stdout.write(`  Fetched ${Math.min(i + CONCURRENCY, names.length)}/${names.length}...\r`);
    }
  }
  return results;
}

// 1. Get all enemy names
console.log('Fetching enemy names...');
const namesRes = await fetch(`${API_BASE}/enemies?query=names&matchCategories=true`);
const allNames = await namesRes.json();
console.log(`Found ${allNames.length} enemy names.`);

// 2. Fetch each enemy
console.log('Fetching enemy details...');
const rawEnemies = await fetchAll(allNames);
console.log(`\nFetched ${rawEnemies.filter(Boolean).length} enemies successfully.`);

// 3. Map to our format
const enemies = [];
const seenIds = new Set();

for (const data of rawEnemies) {
  if (!data) continue;

  const name = data.name;
  if (!name) continue;

  // Build stable kebab-case id
  const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  // Deduplicate
  if (seenIds.has(id)) continue;
  seenIds.add(id);

  const iconFilename = data.images?.filename_icon;
  const image = iconFilename ? `${ICON_BASE}${iconFilename}.png` : null;

  const enemyType = data.enemyType || 'COMMON';
  const category = data.categoryText || '';
  const description = data.description || '';

  enemies.push({ id, name, enemyType, category, description, image });
}

// 4. Sort: bosses first, then by category, then alphabetically
const TYPE_ORDER = { BOSS: 0, ELITE: 1, COMMON: 2 };
enemies.sort((a, b) => {
  const typeA = TYPE_ORDER[a.enemyType] ?? 3;
  const typeB = TYPE_ORDER[b.enemyType] ?? 3;
  if (typeA !== typeB) return typeA - typeB;
  if (a.category !== b.category) return a.category.localeCompare(b.category);
  return a.name.localeCompare(b.name);
});

// 5. Generate file
const enemyLines = enemies.map((e) => {
  const image = e.image ? `'${e.image}'` : 'null';
  const desc = e.description.replace(/'/g, "\\'").replace(/\n/g, '\\n');
  return `  {
    id: '${e.id}',
    name: '${e.name.replace(/'/g, "\\'")}',
    enemyType: '${e.enemyType}',
    category: '${e.category.replace(/'/g, "\\'")}',
    description: '${desc}',
    image: ${image},
  },`;
});

const output = `// Auto-generated by scripts/fetch-enemies.js
// Source: genshin-db-api (https://github.com/theBowja/genshin-db-api)
// Run \`npm run fetch:enemies\` to regenerate.

export const enemies = [
${enemyLines.join('\n')}
];
`;

const outPath = join(__dirname, '..', 'src', 'data', 'enemies.js');
writeFileSync(outPath, output, 'utf-8');
console.log(`✓ Written ${enemies.length} enemies to src/data/enemies.js`);
